### ISSUE TITLE
Add option to only install selected exotic libraries only

### ISSUE THREAD

**Issue by Thecarisma** [exoticlibraries/exotic-action#8]
```yml
   - name: Setup Exotic Libraries
        uses: exoticlibraries/exotic-action@v1.1
        with:
          download-exotic-libraries: true
          run-regression: false
          selected-exotic-libraries: |
             libcester
             libxbench
             
```
